// Copyright (c) 2025-2026 Peter Fors
// SPDX-License-Identifier: MIT

#pragma once

enum {
	MKFW_KEY_SPACE = ' ',				// 0x20
	MKFW_KEY_EXCLAMATION = '!',		// 0x21
	MKFW_KEY_QUOTE = '"',				// 0x22
	MKFW_KEY_HASH = '#',				// 0x23
	MKFW_KEY_DOLLAR = '$',			// 0x24
	MKFW_KEY_PERCENT = '%',			// 0x25
	MKFW_KEY_AMPERSAND = '&',		// 0x26
	MKFW_KEY_APOSTROPHE = '\'',		// 0x27
	MKFW_KEY_LEFT_PAREN = '(',		// 0x28
	MKFW_KEY_RIGHT_PAREN = ')',		// 0x29
	MKFW_KEY_ASTERISK = '*',			// 0x2A
	MKFW_KEY_PLUS = '+',				// 0x2B
	MKFW_KEY_COMMA = ',',				// 0x2C
	MKFW_KEY_MINUS = '-',				// 0x2D
	MKFW_KEY_PERIOD = '.',			// 0x2E
	MKFW_KEY_SLASH = '/',				// 0x2F
	MKFW_KEY_0 = '0',					// 0x30
	MKFW_KEY_1 = '1',					// 0x31
	MKFW_KEY_2 = '2',					// 0x32
	MKFW_KEY_3 = '3',					// 0x33
	MKFW_KEY_4 = '4',					// 0x34
	MKFW_KEY_5 = '5',					// 0x35
	MKFW_KEY_6 = '6',					// 0x36
	MKFW_KEY_7 = '7',					// 0x37
	MKFW_KEY_8 = '8',					// 0x38
	MKFW_KEY_9 = '9',					// 0x39
	MKFW_KEY_COLON = ':',				// 0x3A
	MKFW_KEY_SEMICOLON = ';',		// 0x3B
	MKFW_KEY_LESS = '<',				// 0x3C
	MKFW_KEY_EQUAL = '=',				// 0x3D
	MKFW_KEY_GREATER = '>',			// 0x3E
	MKFW_KEY_QUESTION = '?',			// 0x3F
	MKFW_KEY_AT = '@',					// 0x40
	MKFW_KEY_A = 'a',					// 0x61
	MKFW_KEY_B = 'b',					// 0x62
	MKFW_KEY_C = 'c',					// 0x63
	MKFW_KEY_D = 'd',					// 0x64
	MKFW_KEY_E = 'e',					// 0x65
	MKFW_KEY_F = 'f',					// 0x66
	MKFW_KEY_G = 'g',					// 0x67
	MKFW_KEY_H = 'h',					// 0x68
	MKFW_KEY_I = 'i',					// 0x69
	MKFW_KEY_J = 'j',					// 0x6A
	MKFW_KEY_K = 'k',					// 0x6B
	MKFW_KEY_L = 'l',					// 0x6C
	MKFW_KEY_M = 'm',					// 0x6D
	MKFW_KEY_N = 'n',					// 0x6E
	MKFW_KEY_O = 'o',					// 0x6F
	MKFW_KEY_P = 'p',					// 0x70
	MKFW_KEY_Q = 'q',					// 0x71
	MKFW_KEY_R = 'r',					// 0x72
	MKFW_KEY_S = 's',					// 0x73
	MKFW_KEY_T = 't',					// 0x74
	MKFW_KEY_U = 'u',					// 0x75
	MKFW_KEY_V = 'v',					// 0x76
	MKFW_KEY_W = 'w',					// 0x77
	MKFW_KEY_X = 'x',					// 0x78
	MKFW_KEY_Y = 'y',					// 0x79
	MKFW_KEY_Z = 'z',					// 0x7A
	MKFW_KEY_LEFT_BRACKET = '[',	// 0x5B
	MKFW_KEY_BACKSLASH = '\\',		// 0x5C
	MKFW_KEY_RIGHT_BRACKET = ']',	// 0x5D
	MKFW_KEY_CARET = '^',				// 0x5E
	MKFW_KEY_UNDERSCORE = '_',		// 0x5F
	MKFW_KEY_GRAVE = '`',				// 0x60
	MKFW_KEY_LEFT_BRACE = '{',		// 0x7B
	MKFW_KEY_PIPE = '|',				// 0x7C
	MKFW_KEY_RIGHT_BRACE = '}',		// 0x7D
	MKFW_KEY_TILDE = '~',				// 0x7E

	MKFW_KEY_ESCAPE = 190,
	MKFW_KEY_LEFT,
	MKFW_KEY_RIGHT,
	MKFW_KEY_UP,
	MKFW_KEY_DOWN,
	MKFW_KEY_RETURN,
	MKFW_KEY_TAB,
	MKFW_KEY_BACKSPACE,
	MKFW_KEY_SHIFT,
	MKFW_KEY_LSHIFT,
	MKFW_KEY_RSHIFT,
	MKFW_KEY_LCTRL,
	MKFW_KEY_RCTRL,
	MKFW_KEY_LALT,
	MKFW_KEY_RALT,
	MKFW_KEY_CTRL,
	MKFW_KEY_ALT,
	MKFW_KEY_CAPSLOCK,
	MKFW_KEY_F1,
	MKFW_KEY_F2,
	MKFW_KEY_F3,
	MKFW_KEY_F4,
	MKFW_KEY_F5,
	MKFW_KEY_F6,
	MKFW_KEY_F7,
	MKFW_KEY_F8,
	MKFW_KEY_F9,
	MKFW_KEY_F10,
	MKFW_KEY_F11,
	MKFW_KEY_F12,

	// Additional Keys (Sequentially After F12)
	MKFW_KEY_DELETE,
	MKFW_KEY_INSERT,
	MKFW_KEY_HOME,
	MKFW_KEY_END,
	MKFW_KEY_PAGEUP,
	MKFW_KEY_PAGEDOWN,
	MKFW_KEY_NUMLOCK,
	MKFW_KEY_SCROLLLOCK,
	MKFW_KEY_PRINTSCREEN,
	MKFW_KEY_PAUSE,
	MKFW_KEY_MENU,

	// Numpad Keys (When Distinct from Top Row Numbers)
	MKFW_KEY_NUMPAD_0,
	MKFW_KEY_NUMPAD_1,
	MKFW_KEY_NUMPAD_2,
	MKFW_KEY_NUMPAD_3,
	MKFW_KEY_NUMPAD_4,
	MKFW_KEY_NUMPAD_5,
	MKFW_KEY_NUMPAD_6,
	MKFW_KEY_NUMPAD_7,
	MKFW_KEY_NUMPAD_8,
	MKFW_KEY_NUMPAD_9,
	MKFW_KEY_NUMPAD_DECIMAL,
	MKFW_KEY_NUMPAD_DIVIDE,
	MKFW_KEY_NUMPAD_MULTIPLY,
	MKFW_KEY_NUMPAD_SUBTRACT,
	MKFW_KEY_NUMPAD_ADD,
	MKFW_KEY_NUMPAD_ENTER,
	MKFW_KEY_LSUPER,
	MKFW_KEY_RSUPER,
	MKFW_KEY_LAST,					// NOTE(peter): Make sure this is <= 256
};

enum {
	MKFW_RELEASED = 0,
	MKFW_PRESSED
};

enum {
	MKFW_MOUSE_LEFT = 0,
	MKFW_MOUSE_MIDDLE,
	MKFW_MOUSE_RIGHT,
	MKFW_MOUSE_EXTRA1,
	MKFW_MOUSE_EXTRA2,
};

enum {
	MKFW_CURSOR_ARROW = 0,
	MKFW_CURSOR_TEXT_INPUT,
	MKFW_CURSOR_RESIZE_ALL,
	MKFW_CURSOR_RESIZE_NS,
	MKFW_CURSOR_RESIZE_EW,
	MKFW_CURSOR_RESIZE_NESW,
	MKFW_CURSOR_RESIZE_NWSE,
	MKFW_CURSOR_HAND,
	MKFW_CURSOR_NOT_ALLOWED,
	MKFW_CURSOR_LAST,
};

enum {
	MKFW_MODIFIER_SHIFT = 0,
	MKFW_MODIFIER_CTRL,
	MKFW_MODIFIER_ALT,
	MKFW_MODIFIER_LAST
};

#define MKFW_MOD_LSHIFT  0x01
#define MKFW_MOD_RSHIFT  0x02
#define MKFW_MOD_LCTRL   0x04
#define MKFW_MOD_RCTRL   0x08
#define MKFW_MOD_LALT    0x10
#define MKFW_MOD_RALT    0x20
#define MKFW_MOD_LSUPER  0x40
#define MKFW_MOD_RSUPER  0x80

#define MKFW_MOD_SHIFT   (MKFW_MOD_LSHIFT | MKFW_MOD_RSHIFT)
#define MKFW_MOD_CTRL    (MKFW_MOD_LCTRL | MKFW_MOD_RCTRL)
#define MKFW_MOD_ALT     (MKFW_MOD_LALT | MKFW_MOD_RALT)
#define MKFW_MOD_SUPER   (MKFW_MOD_LSUPER | MKFW_MOD_RSUPER)

