// Copyright (c) 2025-2026 Peter Fors
// SPDX-License-Identifier: MIT

#pragma once

enum {
	MKFW_KEY_SPACE = ' ',				// 0x20
	MKFW_KEY_EXCLAMATION = '!',		// 0x21
	MKFW_KEY_QUOTE = '"',				// 0x22
	MKFW_KEY_HASH = '#',				// 0x23
	MKFW_KEY_DOLLAR = '$',			// 0x24
	MKFW_KEY_PERCENT = '%',			// 0x25
	MKFW_KEY_AMPERSAND = '&',		// 0x26
	MKFW_KEY_APOSTROPHE = '\'',		// 0x27
	MKFW_KEY_LEFT_PAREN = '(',		// 0x28
	MKFW_KEY_RIGHT_PAREN = ')',		// 0x29
	MKFW_KEY_ASTERISK = '*',			// 0x2A
	MKFW_KEY_PLUS = '+',				// 0x2B
	MKFW_KEY_COMMA = ',',				// 0x2C
	MKFW_KEY_MINUS = '-',				// 0x2D
	MKFW_KEY_PERIOD = '.',			// 0x2E
	MKFW_KEY_SLASH = '/',				// 0x2F
	MKFW_KEY_0 = '0',					// 0x30
	MKFW_KEY_1 = '1',					// 0x31
	MKFW_KEY_2 = '2',					// 0x32
	MKFW_KEY_3 = '3',					// 0x33
	MKFW_KEY_4 = '4',					// 0x34
	MKFW_KEY_5 = '5',					// 0x35
	MKFW_KEY_6 = '6',					// 0x36
	MKFW_KEY_7 = '7',					// 0x37
	MKFW_KEY_8 = '8',					// 0x38
	MKFW_KEY_9 = '9',					// 0x39
	MKFW_KEY_COLON = ':',				// 0x3A
	MKFW_KEY_SEMICOLON = ';',		// 0x3B
	MKFW_KEY_LESS = '<',				// 0x3C
	MKFW_KEY_EQUAL = '=',				// 0x3D
	MKFW_KEY_GREATER = '>',			// 0x3E
	MKFW_KEY_QUESTION = '?',			// 0x3F
	MKFW_KEY_AT = '@',					// 0x40
	MKFW_KEY_A = 'a',					// 0x61
	MKFW_KEY_B = 'b',					// 0x62
	MKFW_KEY_C = 'c',					// 0x63
	MKFW_KEY_D = 'd',					// 0x64
	MKFW_KEY_E = 'e',					// 0x65
	MKFW_KEY_F = 'f',					// 0x66
	MKFW_KEY_G = 'g',					// 0x67
	MKFW_KEY_H = 'h',					// 0x68
	MKFW_KEY_I = 'i',					// 0x69
	MKFW_KEY_J = 'j',					// 0x6A
	MKFW_KEY_K = 'k',					// 0x6B
	MKFW_KEY_L = 'l',					// 0x6C
	MKFW_KEY_M = 'm',					// 0x6D
	MKFW_KEY_N = 'n',					// 0x6E
	MKFW_KEY_O = 'o',					// 0x6F
	MKFW_KEY_P = 'p',					// 0x70
	MKFW_KEY_Q = 'q',					// 0x71
	MKFW_KEY_R = 'r',					// 0x72
	MKFW_KEY_S = 's',					// 0x73
	MKFW_KEY_T = 't',					// 0x74
	MKFW_KEY_U = 'u',					// 0x75
	MKFW_KEY_V = 'v',					// 0x76
	MKFW_KEY_W = 'w',					// 0x77
	MKFW_KEY_X = 'x',					// 0x78
	MKFW_KEY_Y = 'y',					// 0x79
	MKFW_KEY_Z = 'z',					// 0x7A
	MKFW_KEY_LEFT_BRACKET = '[',	// 0x5B
	MKFW_KEY_BACKSLASH = '\\',		// 0x5C
	MKFW_KEY_RIGHT_BRACKET = ']',	// 0x5D
	MKFW_KEY_CARET = '^',				// 0x5E
	MKFW_KEY_UNDERSCORE = '_',		// 0x5F
	MKFW_KEY_GRAVE = '`',				// 0x60
	MKFW_KEY_LEFT_BRACE = '{',		// 0x7B
	MKFW_KEY_PIPE = '|',				// 0x7C
	MKFW_KEY_RIGHT_BRACE = '}',		// 0x7D
	MKFW_KEY_TILDE = '~',				// 0x7E

	MKFW_KEY_ESCAPE = 190,
	MKFW_KEY_LEFT,
	MKFW_KEY_RIGHT,
	MKFW_KEY_UP,
	MKFW_KEY_DOWN,
	MKFW_KEY_RETURN,
	MKFW_KEY_TAB,
	MKFW_KEY_BACKSPACE,
	MKFW_KEY_SHIFT,
	MKFW_KEY_LSHIFT,
	MKFW_KEY_RSHIFT,
	MKFW_KEY_LCTRL,
	MKFW_KEY_RCTRL,
	MKFW_KEY_LALT,
	MKFW_KEY_RALT,
	MKFW_KEY_CTRL,
	MKFW_KEY_ALT,
	MKFW_KEY_CAPSLOCK,
	MKFW_KEY_F1,
	MKFW_KEY_F2,
	MKFW_KEY_F3,
	MKFW_KEY_F4,
	MKFW_KEY_F5,
	MKFW_KEY_F6,
	MKFW_KEY_F7,
	MKFW_KEY_F8,
	MKFW_KEY_F9,
	MKFW_KEY_F10,
	MKFW_KEY_F11,
	MKFW_KEY_F12,

	// Additional Keys (Sequentially After F12)
	MKFW_KEY_DELETE,
	MKFW_KEY_INSERT,
	MKFW_KEY_HOME,
	MKFW_KEY_END,
	MKFW_KEY_PAGEUP,
	MKFW_KEY_PAGEDOWN,
	MKFW_KEY_NUMLOCK,
	MKFW_KEY_SCROLLLOCK,
	MKFW_KEY_PRINTSCREEN,
	MKFW_KEY_PAUSE,
	MKFW_KEY_MENU,

	// Numpad Keys (When Distinct from Top Row Numbers)
	MKFW_KEY_NUMPAD_0,
	MKFW_KEY_NUMPAD_1,
	MKFW_KEY_NUMPAD_2,
	MKFW_KEY_NUMPAD_3,
	MKFW_KEY_NUMPAD_4,
	MKFW_KEY_NUMPAD_5,
	MKFW_KEY_NUMPAD_6,
	MKFW_KEY_NUMPAD_7,
	MKFW_KEY_NUMPAD_8,
	MKFW_KEY_NUMPAD_9,
	MKFW_KEY_NUMPAD_DECIMAL,
	MKFW_KEY_NUMPAD_DIVIDE,
	MKFW_KEY_NUMPAD_MULTIPLY,
	MKFW_KEY_NUMPAD_SUBTRACT,
	MKFW_KEY_NUMPAD_ADD,
	MKFW_KEY_NUMPAD_ENTER,
	MKFW_KEY_LSUPER,
	MKFW_KEY_RSUPER,
	MKFW_KEY_LAST,					// NOTE(peter): Make sure this is <= 256
};

enum {
	MKFW_RELEASED = 0,
	MKFW_PRESSED
};

enum {
	MKFW_MOUSE_LEFT = 0,
	MKFW_MOUSE_MIDDLE,
	MKFW_MOUSE_RIGHT,
	MKFW_MOUSE_EXTRA1,
	MKFW_MOUSE_EXTRA2,
};

enum {
	MKFW_CURSOR_ARROW = 0,
	MKFW_CURSOR_TEXT_INPUT,
	MKFW_CURSOR_RESIZE_ALL,
	MKFW_CURSOR_RESIZE_NS,
	MKFW_CURSOR_RESIZE_EW,
	MKFW_CURSOR_RESIZE_NESW,
	MKFW_CURSOR_RESIZE_NWSE,
	MKFW_CURSOR_HAND,
	MKFW_CURSOR_NOT_ALLOWED,
	MKFW_CURSOR_LAST,
};

// Scancodes (USB HID Usage Page 7).  Identify a key by its physical
// position on the keyboard, independent of layout / locale.  Use
// these for "the key in the W position regardless of QWERTY/AZERTY"
// (the textbook WASD-on-AZERTY case).  For text-meaning input use
// the MKFW_KEY_* values delivered by the key callback.
enum {
	MKFW_SCANCODE_A = 0x04,
	MKFW_SCANCODE_B = 0x05,
	MKFW_SCANCODE_C = 0x06,
	MKFW_SCANCODE_D = 0x07,
	MKFW_SCANCODE_E = 0x08,
	MKFW_SCANCODE_F = 0x09,
	MKFW_SCANCODE_G = 0x0a,
	MKFW_SCANCODE_H = 0x0b,
	MKFW_SCANCODE_I = 0x0c,
	MKFW_SCANCODE_J = 0x0d,
	MKFW_SCANCODE_K = 0x0e,
	MKFW_SCANCODE_L = 0x0f,
	MKFW_SCANCODE_M = 0x10,
	MKFW_SCANCODE_N = 0x11,
	MKFW_SCANCODE_O = 0x12,
	MKFW_SCANCODE_P = 0x13,
	MKFW_SCANCODE_Q = 0x14,
	MKFW_SCANCODE_R = 0x15,
	MKFW_SCANCODE_S = 0x16,
	MKFW_SCANCODE_T = 0x17,
	MKFW_SCANCODE_U = 0x18,
	MKFW_SCANCODE_V = 0x19,
	MKFW_SCANCODE_W = 0x1a,
	MKFW_SCANCODE_X = 0x1b,
	MKFW_SCANCODE_Y = 0x1c,
	MKFW_SCANCODE_Z = 0x1d,

	MKFW_SCANCODE_1 = 0x1e,
	MKFW_SCANCODE_2 = 0x1f,
	MKFW_SCANCODE_3 = 0x20,
	MKFW_SCANCODE_4 = 0x21,
	MKFW_SCANCODE_5 = 0x22,
	MKFW_SCANCODE_6 = 0x23,
	MKFW_SCANCODE_7 = 0x24,
	MKFW_SCANCODE_8 = 0x25,
	MKFW_SCANCODE_9 = 0x26,
	MKFW_SCANCODE_0 = 0x27,

	MKFW_SCANCODE_RETURN     = 0x28,
	MKFW_SCANCODE_ESCAPE     = 0x29,
	MKFW_SCANCODE_BACKSPACE  = 0x2a,
	MKFW_SCANCODE_TAB        = 0x2b,
	MKFW_SCANCODE_SPACE      = 0x2c,

	MKFW_SCANCODE_MINUS         = 0x2d,
	MKFW_SCANCODE_EQUAL         = 0x2e,
	MKFW_SCANCODE_LEFT_BRACKET  = 0x2f,
	MKFW_SCANCODE_RIGHT_BRACKET = 0x30,
	MKFW_SCANCODE_BACKSLASH     = 0x31,
	MKFW_SCANCODE_SEMICOLON     = 0x33,
	MKFW_SCANCODE_APOSTROPHE    = 0x34,
	MKFW_SCANCODE_GRAVE         = 0x35,
	MKFW_SCANCODE_COMMA         = 0x36,
	MKFW_SCANCODE_PERIOD        = 0x37,
	MKFW_SCANCODE_SLASH         = 0x38,

	MKFW_SCANCODE_CAPSLOCK = 0x39,
	MKFW_SCANCODE_F1  = 0x3a,
	MKFW_SCANCODE_F2  = 0x3b,
	MKFW_SCANCODE_F3  = 0x3c,
	MKFW_SCANCODE_F4  = 0x3d,
	MKFW_SCANCODE_F5  = 0x3e,
	MKFW_SCANCODE_F6  = 0x3f,
	MKFW_SCANCODE_F7  = 0x40,
	MKFW_SCANCODE_F8  = 0x41,
	MKFW_SCANCODE_F9  = 0x42,
	MKFW_SCANCODE_F10 = 0x43,
	MKFW_SCANCODE_F11 = 0x44,
	MKFW_SCANCODE_F12 = 0x45,

	MKFW_SCANCODE_PRINTSCREEN = 0x46,
	MKFW_SCANCODE_SCROLLLOCK  = 0x47,
	MKFW_SCANCODE_PAUSE       = 0x48,
	MKFW_SCANCODE_INSERT      = 0x49,
	MKFW_SCANCODE_HOME        = 0x4a,
	MKFW_SCANCODE_PAGEUP      = 0x4b,
	MKFW_SCANCODE_DELETE      = 0x4c,
	MKFW_SCANCODE_END         = 0x4d,
	MKFW_SCANCODE_PAGEDOWN    = 0x4e,
	MKFW_SCANCODE_RIGHT       = 0x4f,
	MKFW_SCANCODE_LEFT        = 0x50,
	MKFW_SCANCODE_DOWN        = 0x51,
	MKFW_SCANCODE_UP          = 0x52,

	MKFW_SCANCODE_NUMLOCK         = 0x53,
	MKFW_SCANCODE_NUMPAD_DIVIDE   = 0x54,
	MKFW_SCANCODE_NUMPAD_MULTIPLY = 0x55,
	MKFW_SCANCODE_NUMPAD_SUBTRACT = 0x56,
	MKFW_SCANCODE_NUMPAD_ADD      = 0x57,
	MKFW_SCANCODE_NUMPAD_ENTER    = 0x58,
	MKFW_SCANCODE_NUMPAD_1        = 0x59,
	MKFW_SCANCODE_NUMPAD_2        = 0x5a,
	MKFW_SCANCODE_NUMPAD_3        = 0x5b,
	MKFW_SCANCODE_NUMPAD_4        = 0x5c,
	MKFW_SCANCODE_NUMPAD_5        = 0x5d,
	MKFW_SCANCODE_NUMPAD_6        = 0x5e,
	MKFW_SCANCODE_NUMPAD_7        = 0x5f,
	MKFW_SCANCODE_NUMPAD_8        = 0x60,
	MKFW_SCANCODE_NUMPAD_9        = 0x61,
	MKFW_SCANCODE_NUMPAD_0        = 0x62,
	MKFW_SCANCODE_NUMPAD_DECIMAL  = 0x63,

	MKFW_SCANCODE_MENU = 0x65,

	MKFW_SCANCODE_LCTRL  = 0xe0,
	MKFW_SCANCODE_LSHIFT = 0xe1,
	MKFW_SCANCODE_LALT   = 0xe2,
	MKFW_SCANCODE_LSUPER = 0xe3,
	MKFW_SCANCODE_RCTRL  = 0xe4,
	MKFW_SCANCODE_RSHIFT = 0xe5,
	MKFW_SCANCODE_RALT   = 0xe6,
	MKFW_SCANCODE_RSUPER = 0xe7,
};

#define MKFW_MOD_LSHIFT  0x01
#define MKFW_MOD_RSHIFT  0x02
#define MKFW_MOD_LCTRL   0x04
#define MKFW_MOD_RCTRL   0x08
#define MKFW_MOD_LALT    0x10
#define MKFW_MOD_RALT    0x20
#define MKFW_MOD_LSUPER  0x40
#define MKFW_MOD_RSUPER  0x80

#define MKFW_MOD_SHIFT   (MKFW_MOD_LSHIFT | MKFW_MOD_RSHIFT)
#define MKFW_MOD_CTRL    (MKFW_MOD_LCTRL | MKFW_MOD_RCTRL)
#define MKFW_MOD_ALT     (MKFW_MOD_LALT | MKFW_MOD_RALT)
#define MKFW_MOD_SUPER   (MKFW_MOD_LSUPER | MKFW_MOD_RSUPER)

