#!/usr/bin/env python3
# Copyright (c) 2025-2026 Peter Fors
# SPDX-License-Identifier: MIT
#
# Regenerate the controller-mapping data in mkfw_joystick_gamedb.h
# from the upstream SDL_GameControllerDB project.
#
# Usage:
#     python3 tools/gen_joystick_gamedb.py            # fetch + rewrite
#     python3 tools/gen_joystick_gamedb.py --dry-run  # print, don't write
#     python3 tools/gen_joystick_gamedb.py --from-file PATH  # read local copy
#
# The script replaces only the text between the
#     /* BEGIN GENERATED gamedb */
#     /* END GENERATED gamedb */
# marker comments in mkfw_joystick_gamedb.h.  Everything outside the
# markers (the button/axis enums, file header, etc.) is preserved.

import argparse
import os
import sys
import urllib.request

UPSTREAM = "https://raw.githubusercontent.com/mdqinc/SDL_GameControllerDB/master/gamecontrollerdb.txt"
HEADER_PATH = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "mkfw_joystick_gamedb.h"))
MARK_BEGIN = "/* BEGIN GENERATED gamedb */"
MARK_END   = "/* END GENERATED gamedb */"
WANTED_PLATFORMS = ("Linux", "Windows")


def fetch(url):
	with urllib.request.urlopen(url, timeout=60) as r:
		return r.read().decode("utf-8")


def parse(text):
	entries = []
	seen = set()
	for raw in text.splitlines():
		line = raw.strip()
		if not line or line.startswith("#"):
			continue
		if "platform:" not in line:
			continue
		platform = line.split("platform:", 1)[1].split(",")[0].strip()
		if platform not in WANTED_PLATFORMS:
			continue
		# Deduplicate by (guid, platform).  Upstream sometimes has multiple
		# entries for the same GUID; take the first.
		guid = line.split(",", 1)[0].strip()
		key = (guid, platform)
		if key in seen:
			continue
		seen.add(key)
		entries.append(line)
	return entries


def emit(entries, source_url):
	lines = []
	lines.append(MARK_BEGIN)
	lines.append("/* Generated by tools/gen_joystick_gamedb.py from")
	lines.append(f" * {source_url}")
	lines.append(f" * Entries: {len(entries)} (filtered to {' / '.join(WANTED_PLATFORMS)}). */")
	lines.append("static const char mkfw_gamecontrollerdb_data[] =")
	for line in entries:
		esc = line.replace("\\", "\\\\").replace('"', '\\"')
		lines.append(f'\t"{esc}\\n"')
	lines.append('\t"";')
	lines.append(MARK_END)
	return "\n".join(lines) + "\n"


def splice(file_text, generated):
	i = file_text.find(MARK_BEGIN)
	j = file_text.find(MARK_END)
	if i < 0 or j < 0:
		raise SystemExit(f"missing markers in {HEADER_PATH}")
	if j < i:
		raise SystemExit("END marker found before BEGIN marker")
	j_end = j + len(MARK_END)
	return file_text[:i] + generated.rstrip() + file_text[j_end:]


def main():
	ap = argparse.ArgumentParser()
	ap.add_argument("--dry-run", action="store_true", help="print the generated block to stdout instead of writing")
	ap.add_argument("--from-file", metavar="PATH", help="read upstream DB from a local file instead of fetching")
	ap.add_argument("--url", default=UPSTREAM, help="override upstream URL")
	args = ap.parse_args()

	if args.from_file:
		with open(args.from_file, "r", encoding="utf-8") as f:
			text = f.read()
		source = args.from_file
	else:
		print(f"Fetching {args.url}", file=sys.stderr)
		text = fetch(args.url)
		source = args.url

	entries = parse(text)
	if not entries:
		raise SystemExit("no entries matched after filtering; refusing to overwrite header")

	generated = emit(entries, source)

	if args.dry_run:
		sys.stdout.write(generated)
		return

	with open(HEADER_PATH, "r", encoding="utf-8") as f:
		original = f.read()
	new = splice(original, generated)
	tmp = HEADER_PATH + ".tmp"
	with open(tmp, "w", encoding="utf-8") as f:
		f.write(new)
	os.replace(tmp, HEADER_PATH)
	print(f"Wrote {len(entries)} entries to {HEADER_PATH}", file=sys.stderr)


if __name__ == "__main__":
	main()
